### ISSUE TITLE
不支持web吗？

### ISSUE THREAD

**Issue by 455631680** [Nayuta-D/fps_monitor#9]
![image](https://user-images.githubusercontent.com/7570630/135063207-5446bb93-dc6e-4e15-89a5-6261f6feda3d.png)

**Comment by Nayuta403** [comment]
里面有个属性判断 debug 还是release 的，release不打进去。看起来 web 上拿不到这个变量，直接注了试试。





------------------ 原始邮件 ------------------
发件人: 455631680 ***@***.***&gt;
发送时间: 2021年9月28日 17:38
收件人: Nayuta403/fps_monitor ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[Nayuta403/fps_monitor] 不支持web吗？ (#9)





 

 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
